### ISSUE TITLE
개발자들에게 Issue란 프로젝트에서 발생하는 문제를 의미해~

### ISSUE THREAD

**Issue by jooyounghun** [jonhyuk0922/ML-study#1]
github로 프로젝트를 관리하면서 
여기 issue 란에 코드상에 부족한 부분이나, 보완이 필요한 부분들을 올려놓을 수 있어

Issue 를 통해서 contributor 사람들에게 역할을 줄 수 있고, 코드 상에 특정 부분에 tag를 걸 수 있어서 자주 사용해

@jonhyuk0922

**Comment by jonhyuk0922** [comment]
오 그렇구나!! 이렇게 이슈를 처음 보네!!!!
