### ISSUE TITLE
# 서버 구현을 위한 개발 환경 세팅 1

### ISSUE THREAD

**Issue by jooyounghun** [jonhyuk0922/ML-study#2]
- [ ]  IntelliJ 다운 - 아래에 링크로 들어가서 Community 버전으로 다운 받으면 돼
https://www.jetbrains.com/idea/download/#section=windows

@jonhyuk0922

**Comment by jooyounghun** [comment]
확인하면 체크하고 이슈 닫아줘~~

**Comment by jooyounghun** [comment]
설치 시 고려할 것

1. intelliJ 설치 시 JAVA Path 설정 해주어야 해 https://velog.io/@ednadev/%EC%9D%B8%ED%85%94%EB%A6%AC%EC%A0%9C%EC%9D%B4IntelliJ-%EC%84%A4%EC%B9%98

2. 설치하고 SDK가 없다고 나올텐데 SDK 설치해주면 돼
https://goddaehee.tistory.com/197

**Comment by jonhyuk0922** [comment]
처음에 JAVA로 설정되어있어서 안건드렸고 , SDK는 설치했어! 젤 최신걸로
